# Form implementation generated from reading ui file 'Histograma_Interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon

class Ui_Histograma(object):
    def setupUi(self, Histograma):
        Histograma.setObjectName("Histograma")
        self.setWindowIcon(QIcon('Icons/logoeditor.png'))
        Histograma.resize(609, 552)
        self.centralwidget = QtWidgets.QWidget(parent=Histograma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GraphicHisto = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.GraphicHisto.setObjectName("GraphicHisto")
        self.verticalLayout.addWidget(self.GraphicHisto)
        self.ButtonEqualizar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonEqualizar.setObjectName("ButtonEqualizar")
        self.verticalLayout.addWidget(self.ButtonEqualizar)
        Histograma.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Histograma)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 22))
        self.menubar.setObjectName("menubar")
        Histograma.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Histograma)
        self.statusbar.setObjectName("statusbar")
        Histograma.setStatusBar(self.statusbar)

        self.retranslateUi(Histograma)
        QtCore.QMetaObject.connectSlotsByName(Histograma)

    def retranslateUi(self, Histograma):
        _translate = QtCore.QCoreApplication.translate
        Histograma.setWindowTitle(_translate("Histograma", "Histograma"))
        self.ButtonEqualizar.setText(_translate("Histograma", "Equalizar Histograma"))
