# Form implementation generated from reading ui file 'OrigInterface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImagemOriginal(object):
    def setupUi(self, ImagemOriginal):
        ImagemOriginal.setObjectName("ImagemOriginal")
        ImagemOriginal.setEnabled(True)
        ImagemOriginal.resize(691, 547)
        self.centralwidget = QtWidgets.QWidget(parent=ImagemOriginal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InfoOrig = QtWidgets.QLabel(parent=self.centralwidget)
        self.InfoOrig.setText("")
        self.InfoOrig.setObjectName("InfoOrig")
        self.verticalLayout.addWidget(self.InfoOrig, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.GraphicOrig = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.GraphicOrig.setObjectName("GraphicOrig")
        self.verticalLayout.addWidget(self.GraphicOrig)
        ImagemOriginal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ImagemOriginal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 22))
        self.menubar.setObjectName("menubar")
        ImagemOriginal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ImagemOriginal)
        self.statusbar.setObjectName("statusbar")
        ImagemOriginal.setStatusBar(self.statusbar)

        self.retranslateUi(ImagemOriginal)
        QtCore.QMetaObject.connectSlotsByName(ImagemOriginal)

    def retranslateUi(self, ImagemOriginal):
        _translate = QtCore.QCoreApplication.translate
        ImagemOriginal.setWindowTitle(_translate("ImagemOriginal", "Imagem Original"))
