# Form implementation generated from reading ui file 'sobelinterface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon


class Ui_SobelWindow(object):
    def setupUi(self, SobelWindow):
        SobelWindow.setObjectName("SobelWindow")
        self.setWindowIcon(QIcon('Icons/logoeditor.png'))
        SobelWindow.resize(609, 746)
        self.centralwidget = QtWidgets.QWidget(parent=SobelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SobelLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.SobelLabel.setText("")
        self.SobelLabel.setObjectName("SobelLabel")
        self.verticalLayout.addWidget(self.SobelLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.GraphicViewSobel = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.GraphicViewSobel.setObjectName("GraphicViewSobel")
        self.verticalLayout.addWidget(self.GraphicViewSobel)
        self.AplicarSobel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AplicarSobel.setObjectName("AplicarSobel")
        self.verticalLayout.addWidget(self.AplicarSobel)
        SobelWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SobelWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 22))
        self.menubar.setObjectName("menubar")
        SobelWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SobelWindow)
        self.statusbar.setObjectName("statusbar")
        SobelWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SobelWindow)
        QtCore.QMetaObject.connectSlotsByName(SobelWindow)

    def retranslateUi(self, SobelWindow):
        _translate = QtCore.QCoreApplication.translate
        SobelWindow.setWindowTitle(_translate("SobelWindow", "Sobel Image"))
        self.AplicarSobel.setText(_translate("SobelWindow", "Aplicar"))
